version: "3.8"
services:
  serving:
    image: tensorflow/serving
    environment:
      - MODEL_NAME=mnist
    expose:
      - 8500
      - 8501
    deploy:
      replicas: 1
    volumes:
      - /Users/zjh/project/tensorflow/serving/models:/models

  client:
    image: tensorflow/tensorflow
    environment:
      - PYTHONPATH=/mnt
    command: tail -f
    deploy:
      replicas: 1
    volumes:
      - /Users/zjh/project/tensorflow/serving:/mnt
      - /Users/zjh/project/tensorflow/tensorflow:/tensorflow
